#!/usr/bin/env bash
# Generate per-mixin kustomize bases under base/<mixin>/.
# Each mixin is a standalone kustomize base so overlays can pick the
# combination they want (e.g. some clusters don't run Ceph).
#
# Outputs:
#   base/<mixin>/dashboards/*.json          — Grafana dashboard JSONs
#   base/<mixin>/prometheusrules/*.yaml     — one PrometheusRule CR per group
#                                             (kubernetes-mixin only; ceph
#                                             alerts come from the Rook chart)
#   base/<mixin>/kustomization.yaml         — references the above with the
#                                             grafana_folder annotation baked in
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TMP_DIR="tmp"

# (mixin name, Grafana folder, jsonnet dashboards entry, jsonnet rules entry or "")
MIXINS=(
  "kubernetes:Kubernetes:lib/dashboards_kubernetes.jsonnet:lib/prometheusrules.jsonnet"
  "ceph:Ceph:lib/dashboards_ceph.jsonnet:"
)

mkdir -p "$TMP_DIR"

# Wipe any stale base/ content from the previous flat layout.
# Per-mixin trees are recreated below.
find base -mindepth 1 -delete 2>/dev/null || true

# Validate raw alert/recording rules with promtool before wrapping into CRs.
# --lint=none skips lint-level checks (e.g. upstream kubernetes-mixin has a
# known duplicate-rule warning in code_verb:apiserver_request_total:increase1h
# that newer promtool treats as a fatal lint error). Syntax validation still
# runs.
jsonnet -J vendor -S lib/raw_alerts.jsonnet > "$TMP_DIR/raw_alerts.yaml"
jsonnet -J vendor -S lib/raw_rules.jsonnet  > "$TMP_DIR/raw_rules.yaml"
promtool check rules --lint=none "$TMP_DIR/raw_alerts.yaml"
promtool check rules --lint=none "$TMP_DIR/raw_rules.yaml"

for entry in "${MIXINS[@]}"; do
  IFS=':' read -r mixin folder dash_entry rule_entry <<<"$entry"
  out="base/$mixin"
  mkdir -p "$out/dashboards"

  jsonnet -J vendor -m "$out/dashboards" "$dash_entry" >/dev/null

  if [ -n "$rule_entry" ]; then
    mkdir -p "$out/prometheusrules"
    jsonnet -J vendor -S -m "$out/prometheusrules" "$rule_entry" >/dev/null
  fi

  # Regenerate per-mixin kustomization.yaml deterministically.
  {
    cat <<EOF
# AUTO-GENERATED by mixins/scripts/generate.sh -- do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
EOF
    if [ -d "$out/prometheusrules" ] && find "$out/prometheusrules" -maxdepth 1 -name '*.yaml' | head -1 | grep -q .; then
      printf '\nresources:\n'
      (cd "$out" && find prometheusrules -maxdepth 1 -name '*.yaml' | sort | sed 's|^|  - |')
    fi
    printf '\nconfigMapGenerator:\n'
    # One ConfigMap per dashboard with the mixin's grafana_folder annotation
    # baked into generator options. Keeps each object well under the 256 KiB
    # annotation limit that bites when apply records last-applied-configuration.
    (cd "$out" && find dashboards -maxdepth 1 -name '*.json' | sort) \
      | while read -r path; do
          name=$(basename "$path" .json)
          printf '  - name: %s-mixin-dashboard-%s\n    files:\n      - %s\n    options:\n      annotations:\n        grafana_folder: %s\n' \
            "$mixin" "$name" "$path" "$folder"
        done
    cat <<'EOF'

generatorOptions:
  disableNameSuffixHash: false
EOF
  } > "$out/kustomization.yaml"
done

count_files() {
  # Safe under `set -o pipefail` — falls through to 0 when the dir is missing.
  local dir="$1" pattern="$2"
  if [ -d "$dir" ]; then
    find "$dir" -maxdepth 1 -name "$pattern" | wc -l
  else
    echo 0
  fi
}

echo "Generated:"
for entry in "${MIXINS[@]}"; do
  IFS=':' read -r mixin _ _ _ <<<"$entry"
  dcount=$(count_files "base/$mixin/dashboards" '*.json')
  rcount=$(count_files "base/$mixin/prometheusrules" '*.yaml')
  echo "  $mixin: $dcount dashboards, $rcount PrometheusRule CRs"
done
