[crio.runtime.runtimes.kata-clh]
runtime_path = "/opt/kata/runtime-rs/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
runtime_config_path = "/opt/kata/share/defaults/kata-containers/runtime-rs/configuration-clh-runtime-rs.toml"
privileged_without_host_devices = true
