{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "vault-eso.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ (.secretStoreRef).name | default $.Values.secretStore.name | default "vault" }}
    kind: {{ (.secretStoreRef).kind | default "SecretStore" }}
  target:
    name: {{ .name }}
    creationPolicy: {{ .creationPolicy | default "Owner" }}
    {{- if .template }}
    template:
      {{- if .template.engineVersion }}
      engineVersion: {{ .template.engineVersion }}
      {{- end }}
      {{- if .template.type }}
      type: {{ .template.type }}
      {{- end }}
      {{- if .template.mergePolicy }}
      mergePolicy: {{ .template.mergePolicy }}
      {{- end }}
      {{- if .template.metadata }}
      metadata:
        {{- toYaml .template.metadata | nindent 8 }}
      {{- end }}
      {{- if .template.data }}
      data:
        {{- toYaml .template.data | nindent 8 }}
      {{- end }}
    {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
