{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "vault-eso.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server | quote }}
      namespace: {{ .Values.secretStore.vault.namespace | quote }}
      path: {{ .Values.secretStore.vault.path | quote }}
      version: {{ .Values.secretStore.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.vault.auth.mountPath | quote }}
          role: {{ .Values.secretStore.vault.auth.role | quote }}
          serviceAccountRef:
            name: eso
{{- end }}
