{{- if .Values.ingress.enabled -}}
{{- $publicHost := .Values.ingress.publicHost | default (include "keycloak.hostOnly" .Values.hostname.public) -}}
{{- $adminHost := .Values.ingress.adminHost | default (include "keycloak.hostOnly" .Values.hostname.admin) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $adminHost | quote }}
        - {{ $publicHost | quote }}
      {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ $adminHost | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: keycloak-http
                port:
                  number: 8080
    - host: {{ $publicHost | quote }}
      http:
        {{- $publicPaths := list "/js/" "/realms/" "/resources/" "/robots.txt" }}
        paths:
          {{- range $publicPaths }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: keycloak-http
                port:
                  number: 8080
          {{- end }}
{{- end }}
