apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.fullname" . }}-config
  namespace: {{ include "opencloud.namespace" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
data:
  config.json: |-
{{ tpl (.Files.Get "files/config.json.gotmpl") . | indent 4 }}

  app-registry.yaml: |-
{{- if empty .Values.config.appRegistry }}
{{ .Files.Get "files/app-registry.yaml" | indent 4 }}
{{- else }}
{{ toYaml (dict "app_registry" .Values.config.appRegistry) | indent 4 }}
{{- end }}

  csp.yaml: |-
{{- if empty .Values.config.csp }}
{{ tpl (.Files.Get "files/csp.yaml.gotmpl") . | indent 4 }}
{{- else }}
{{ .Values.config.csp | indent 4 }}
{{- end }}

  search.yaml: |-
{{ .Files.Get "files/search.yaml" | indent 4 }}

  banned-password-list.txt: |-
{{- if empty .Values.config.bannedPasswordList }}
{{ .Files.Get "files/banned-password-list.txt" | indent 4 }}
{{- else }}
{{ .Values.config.bannedPasswordList | indent 4 }}
{{- end }}
