apiVersion: v2
name: keycloak
description: Keycloak - Identity and Access Management
type: application
version: 0.1.0
# renovate: datasource=docker depName=quay.io/keycloak/keycloak
appVersion: "26.0.7"
