{
 "title": "Node Exporter / USE Method / Multi-cluster",
 "tags": [ "node-exporter-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  ((\n    instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}\n    *\n    instance:node_num_cpu:sum{job=\"node-exporter\"}\n  ) != 0)\n  / scalar(sum(instance:node_num_cpu:sum{job=\"node-exporter\"}))\n) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}}"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 per CPU)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((\n    instance:node_load1_per_cpu:ratio{job=\"node-exporter\"}\n    / scalar(count(instance:node_load1_per_cpu:ratio{job=\"node-exporter\"}))\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((\n    instance:node_memory_utilisation:ratio{job=\"node-exporter\"}\n    / scalar(count(instance:node_memory_utilisation:ratio{job=\"node-exporter\"}))\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}}"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rds" } },
   "targets": [
    {
     "expr": "sum((\n    instance:node_vmstat_pgmajfault:rate5m{job=\"node-exporter\"}\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum((\n    instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\"}\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}} Receive"
    },
    {
     "expr": "sum((\n    instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\"}\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}} Transmit"
    }
   ]
  },
  {
   "title": "Network Saturation (Drops Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum((\n    instance:node_network_receive_drop_excluding_lo:rate5m{job=\"node-exporter\"}\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}} Receive"
    },
    {
     "expr": "sum((\n    instance:node_network_transmit_drop_excluding_lo:rate5m{job=\"node-exporter\"}\n) != 0) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}} Transmit"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((\n    instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\"}\n    / scalar(count(instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\"}))\n) != 0) by (cluster, device)\n",
     "legendFormat": "{{%(clusterLabel)s}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((\n  instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\"}\n  / scalar(count(instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\"}))\n) != 0) by (cluster, device)\n",
     "legendFormat": "{{%(clusterLabel)s}} {{device}}"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Space Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\n  sum without (device) (\n    max without (fstype, mountpoint, instance, pod) ((\n      node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"} - node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}\n    ) != 0)\n  )\n  / scalar(sum(max without (fstype, mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"})))\n) by (cluster)\n",
     "legendFormat": "{{%(clusterLabel)s}}"
    }
   ]
  }
 ]
}