apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
data:
  pdns.conf: |
    launch=gpgsql
    gpgsql-host={{ required "postgresql.host is required" .Values.postgresql.host }}
    gpgsql-port={{ .Values.postgresql.port }}
    gpgsql-dbname={{ .Values.postgresql.database }}
    include-dir=/etc/powerdns/pdns.d
    local-port=5353
    {{- with .Values.powerdns.config }}
    {{ . | nindent 4 }}
    {{- end }}
