{{/*
Allow the release namespace to be overridden for multi-namespace deployments in combined charts
*/}}
{{- define "cluster.namespace" -}}
  {{- if .Values.namespaceOverride -}}
    {{- .Values.namespaceOverride -}}
  {{- else -}}
    {{- .Release.Namespace -}}
  {{- end -}}
{{- end -}}

{{- define "cluster.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "cluster.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "cluster.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "cluster.labels" -}}
helm.sh/chart: {{ include "cluster.chart" . }}
{{ include "cluster.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "cluster.selectorLabels" -}}
app.kubernetes.io/name: {{ include "cluster.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/part-of: cloudnative-pg
{{- end }}

{{/*
Cluster Image Name. Honours .Values.cluster.imageName if set; otherwise builds the upstream
cloudnative-pg/postgresql image from .Values.version.postgresql. Returns an empty string when
neither is set, so the operator's built-in default image is used.
*/}}
{{- define "cluster.imageName" -}}
    {{- if .Values.cluster.imageName -}}
        {{- .Values.cluster.imageName -}}
    {{- else if .Values.version.postgresql -}}
        {{- printf "ghcr.io/cloudnative-pg/postgresql:%s" .Values.version.postgresql -}}
    {{- end }}
{{- end -}}

{{/*
Cluster Image stanza. Emits `imageName:` only when a value is resolved; otherwise emits nothing
so the CNPG operator falls back to its own default image.
*/}}
{{- define "cluster.image" -}}
{{- $image := include "cluster.imageName" . -}}
{{- if $image }}
imageName: {{ $image }}
{{- end }}
{{- end -}}

{{- define "cluster.postgresUID" -}}
  {{- if ge (int .Values.cluster.postgresUID) 0 -}}
    {{- .Values.cluster.postgresUID }}
  {{- else -}}
    {{- 26 -}}
  {{- end -}}
{{- end -}}

{{- define "cluster.postgresGID" -}}
  {{- if ge (int .Values.cluster.postgresGID) 0 -}}
    {{- .Values.cluster.postgresGID }}
  {{- else -}}
    {{- 26 -}}
  {{- end -}}
{{- end -}}

{{/*
Name of the ObjectStore CR generated by this chart for primary backups.
Defaults to <fullname>-backup.
*/}}
{{- define "cluster.objectStoreName" -}}
{{- default (printf "%s-backup" (include "cluster.fullname" .)) .Values.backups.objectStoreName -}}
{{- end -}}

{{/*
Name of the Secret holding S3 credentials (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY).
Defaults to <fullname>-backup, matching the typical OBC-generated secret name.
*/}}
{{- define "cluster.backupSecretName" -}}
{{- default (printf "%s-backup" (include "cluster.fullname" .)) .Values.backups.s3CredentialsSecret -}}
{{- end -}}
